language: scala
scala:
  - 2.12.4
jdk:
  - oraclejdk8
script: travis_retry sbt ++$TRAVIS_SCALA_VERSION clean test
cache:
  directories:
   - $HOME/.bundle.dep.cache
after_success:
  - "./.deployment/deploy.sh"
env:
  global:
    - USE_TAG_VERSION=true
